# Site
name: 'Alimentazione Salutare'
description: 'Consigli alimentari per invecchiare in salute.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'tobedecided@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    guss:
      name:           Guss
      site:           ???
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Guss. I hope you like it!"
      email:          ???@gmail.com
      twitter:        ???

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: guss
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Date
months_short: 
  - Gen
  - Feb
  - Mar
  - Apr
  - Mag
  - Giu
  - Lug
  - Ago
  - Set
  - Ott
  - Nov
  - Dic


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
